/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package tornadoFx

import tornadofx.*


class MyApp: App(MainView::class) {

}

fun main(args: Array<String>) {
    launch<MyApp>(args)
}

class MainView: View("MyApp"){

    override val root = borderpane() {
        top = label {
            this.text = "abc"
        }
        minWidth =  500.0
        maxWidth = 600.0
        minHeight = 300.0
        maxHeight = 300.0

    }
}